years: [2024, 2025]

storage:
  type: fs
  base_dir: ./data

# storage:
#   type: s3
#   bucket: my-minio-bucket
#   endpoint_url: http://localhost:9000

datasets:
  era5:
    name: reanalysis-era5-single-levels
    url: https://cds.climate.copernicus.eu/api
    key: ${CDSAPI_KEY}
    granularity: monthly
    min_date: 2025-08-01
    request:
      product_type: ["reanalysis"]
      variable:
        - "10m_u_component_of_wind"
        - "10m_v_component_of_wind"
        - "2m_dewpoint_temperature"
        - "2m_temperature"
        # - "mean_sea_level_pressure"
        # - "sea_surface_temperature"
        # - "surface_pressure"
        - "total_precipitation"
        # - "ice_temperature_layer_1"
        # - "ice_temperature_layer_2"
        # - "ice_temperature_layer_3"
        # - "ice_temperature_layer_4"
        # - "maximum_2m_temperature_since_previous_post_processing"
        # - "minimum_2m_temperature_since_previous_post_processing"
        # - "skin_temperature"
        # - "100m_u_component_of_wind"
        # - "100m_v_component_of_wind"
        # - "10m_u_component_of_neutral_wind"
        # - "10m_v_component_of_neutral_wind"
        # - "10m_wind_gust_since_previous_post_processing"
        - "instantaneous_10m_wind_gust"
        # - "mean_boundary_layer_dissipation"
        # - "mean_convective_precipitation_rate"
        # - "mean_convective_snowfall_rate"
        # - "mean_eastward_gravity_wave_surface_stress"
        # - "mean_eastward_turbulent_surface_stress"
        # - "mean_evaporation_rate"
        # - "mean_gravity_wave_dissipation"
        # - "mean_large_scale_precipitation_fraction"
        # - "mean_large_scale_precipitation_rate"
        # - "mean_large_scale_snowfall_rate"
        # - "mean_northward_gravity_wave_surface_stress"
        # - "mean_northward_turbulent_surface_stress"
        # - "mean_potential_evaporation_rate"
        # - "mean_runoff_rate"
        # - "mean_snow_evaporation_rate"
        # - "mean_snowfall_rate"
        # - "mean_snowmelt_rate"
        # - "mean_sub_surface_runoff_rate"
        # - "mean_surface_direct_short_wave_radiation_flux"
        # - "mean_surface_direct_short_wave_radiation_flux_clear_sky"
        # - "mean_surface_downward_long_wave_radiation_flux"
        # - "mean_surface_downward_long_wave_radiation_flux_clear_sky"
        # - "mean_surface_downward_short_wave_radiation_flux"
        # - "mean_surface_downward_short_wave_radiation_flux_clear_sky"
        # - "mean_surface_downward_uv_radiation_flux"
        # - "mean_surface_latent_heat_flux"
        # - "mean_surface_net_long_wave_radiation_flux"
        # - "mean_surface_net_long_wave_radiation_flux_clear_sky"
        # - "mean_surface_net_short_wave_radiation_flux"
        # - "mean_surface_net_short_wave_radiation_flux_clear_sky"
        # - "mean_surface_runoff_rate"
        # - "mean_surface_sensible_heat_flux"
        # - "mean_top_downward_short_wave_radiation_flux"
        # - "mean_top_net_long_wave_radiation_flux"
        # - "mean_top_net_long_wave_radiation_flux_clear_sky"
        # - "mean_top_net_short_wave_radiation_flux"
        # - "mean_top_net_short_wave_radiation_flux_clear_sky"
        # - "mean_total_precipitation_rate"
        # - "mean_vertically_integrated_moisture_divergence"
        - "clear_sky_direct_solar_radiation_at_surface"
        # - "downward_uv_radiation_at_the_surface"
        # - "forecast_logarithm_of_surface_roughness_for_heat"
        - "instantaneous_surface_sensible_heat_flux"
        # - "near_ir_albedo_for_diffuse_radiation"
        # - "near_ir_albedo_for_direct_radiation"
        # - "surface_latent_heat_flux"
        - "surface_net_solar_radiation"
        # - "surface_net_solar_radiation_clear_sky"
        - "surface_net_thermal_radiation"
        # - "surface_net_thermal_radiation_clear_sky"
        # - "surface_sensible_heat_flux"
        # - "surface_solar_radiation_downward_clear_sky"
        # - "surface_solar_radiation_downwards"
        # - "surface_thermal_radiation_downward_clear_sky"
        # - "surface_thermal_radiation_downwards"
        # - "toa_incident_solar_radiation"
        # - "top_net_solar_radiation"
        # - "top_net_solar_radiation_clear_sky"
        # - "top_net_thermal_radiation"
        # - "top_net_thermal_radiation_clear_sky"
        # - "total_sky_direct_solar_radiation_at_surface"
        # - "uv_visible_albedo_for_diffuse_radiation"
        # - "uv_visible_albedo_for_direct_radiation"
        - "cloud_base_height"
        # - "high_cloud_cover"
        # - "low_cloud_cover"
        # - "medium_cloud_cover"
        # - "total_cloud_cover"
        # - "total_column_cloud_ice_water"
        # - "total_column_cloud_liquid_water"
        # - "vertical_integral_of_divergence_of_cloud_frozen_water_flux"
        # - "vertical_integral_of_divergence_of_cloud_liquid_water_flux"
        # - "vertical_integral_of_eastward_cloud_frozen_water_flux"
        # - "vertical_integral_of_eastward_cloud_liquid_water_flux"
        # - "vertical_integral_of_northward_cloud_frozen_water_flux"
        # - "vertical_integral_of_northward_cloud_liquid_water_flux"
        # - "lake_bottom_temperature"
        # - "lake_cover"
        # - "lake_depth"
        # - "lake_ice_depth"
        # - "lake_ice_temperature"
        # - "lake_mix_layer_depth"
        # - "lake_mix_layer_temperature"
        # - "lake_shape_factor"
        # - "lake_total_layer_temperature"
        # - "evaporation"
        # - "potential_evaporation"
        # - "runoff"
        # - "sub_surface_runoff"
        # - "surface_runoff"
        # - "convective_precipitation"
        # - "convective_rain_rate"
        # - "instantaneous_large_scale_surface_precipitation_fraction"
        - "large_scale_rain_rate"
        - "large_scale_precipitation"
        # - "large_scale_precipitation_fraction"
        # - "maximum_total_precipitation_rate_since_previous_post_processing"
        # - "minimum_total_precipitation_rate_since_previous_post_processing"
        - "precipitation_type"
        # - "total_column_rain_water"
        # - "convective_snowfall"
        # - "convective_snowfall_rate_water_equivalent"
        # - "large_scale_snowfall_rate_water_equivalent"
        - "large_scale_snowfall"
        # - "snow_albedo"
        # - "snow_density"
        - "snow_depth"
        # - "snow_evaporation"
        - "snowfall"
        - "snowmelt"
        # - "temperature_of_snow_layer"
        # - "total_column_snow_water"
        # - "soil_temperature_level_1"
        # - "soil_temperature_level_2"
        # - "soil_temperature_level_3"
        # - "soil_temperature_level_4"
        # - "soil_type"
        # - "volumetric_soil_water_layer_1"
        # - "volumetric_soil_water_layer_2"
        # - "volumetric_soil_water_layer_3"
        # - "volumetric_soil_water_layer_4"
        - "high_vegetation_cover"
        # - "leaf_area_index_high_vegetation"
        # - "leaf_area_index_low_vegetation"
        - "low_vegetation_cover"
        - "type_of_high_vegetation"
        - "type_of_low_vegetation"
        - "k_index"
        - "maximum_individual_wave_height"
        - "zero_degree_level"
        - "friction_velocity"
      time: ["00:00", "06:00", "12:00", "18:00"]
      data_format: grib
      download_format: unarchived
      area: [45.96, 11.11, 45.84, 11.36]

  cams:
    name: cams-global-reanalysis-eac4-monthly
    url: https://ads.atmosphere.copernicus.eu/api
    key: ${ADSAPI_KEY}
    granularity: monthly
    request:
      variable: [carbon_monoxide, nitrogen_dioxide, temperature]
      pressure_level: ["1", "50", "1000"]
      product_type: ["monthly_mean_by_hour_of_day"]
      time: ["00:00", "12:00"]
      data_format: grib
      area: [45.96, 11.11, 45.84, 11.36]
